require('lspsaga').setup {
	finder = {
		layout = 'float',
		max_height = 0.4,
		left_width = 0.2,
		right_width = 0.45,
		keys = {
			shuttle = '[w',
			toggle_or_open = 'o',
			vsplit = 'v',
			split = 's',
			tabe = 't',
			tabnew = 'r',
			quit = 'q',
			close = '<ESC>',
		},
	},
	definition = {
		height = 0.4,
		width = 0.8,
		edit = 'o',
		vsplit = 'v',
		split = 's',
		tabe = 't',
		quit = 'q',
	},
	code_action = {
		num_shortcut = true,
		show_server_name = true,
		extend_gitsigns = true,
		keys = {
			quit = 'q',
			exec = '<CR>',
		},
	},
	lightbulb = {
		enable = true,
		sign = false,
		virtual_text = true,
	},
	hover = {
		max_width = 0.4,
		max_height = 0.4,
		open_link = 'ob',
		open_browser = '!brave',
	},
	diagnostic = {
		extend_relatedInformation = false,
		max_width = 0.4,
		max_height = 0.4,
		keys = {
			exec_action = 'o',
			quit = 'q',
			toggle_or_jump = '<CR>',
			quit_in_show = { 'q', '<ESC>' },
		},
	},
	rename = {
		in_select = true,
		quit = 'q',
		exec = '<CR>',
		select = 'x',
		confirm = '<CR>',
	},
	outline = {
		win_width = 40,
		auto_preview = true,
		detail = false,
		auto_close = false,
		keys = {
			jump = 'e',
			toggle_or_jump = 'o',
			quit = 'q',
		},
	},
	callhierarchy = {
		keys = {
			edit = 'e',
			vsplit = 'v',
			split = 's',
			tabe = 't',
			shuttle = '[w',
			toggle_or_req = 'u',
			quit = 'q',
			close = '<ESC>',
		},
	},
	symbol_in_winbar = {
		enable = false,
		separator = ' ',
		hide_keyword = true,
		show_file = true,
		folder_level = 2,
		color_mode = true,
		delay = 300,
	},
	beacon = {
		enable = true,
		frequency = 7,
	},
	ui = {
		border = 'single',
		devicon = true,
		title = true,
		winblend = 0,
		expand = '',
		collapse = '',
		code_action = ' ',
		actionfix = '󰁨 ',
		imp_sign = '󰙅 ',
		hover = 'TEST',
	},
}
