require('symbols-outline').setup {
	position = 'right',
	width = 35,
	relative_width = false,
	show_symbol_details = false,
	show_guides = true,
	fold_markers = { '🢒', '🢓' },
	keymaps = {
		close = { '<Esc>', 'q' },
		goto_location = '<Cr>',
		focus_location = 'o',
		hover_symbol = '<C-space>',
		toggle_preview = 'K',
		rename_symbol = 'r',
		code_actions = 'a',
		fold = 'h',
		unfold = 'l',
		fold_all = 'W',
		unfold_all = 'E',
		fold_reset = 'R',
	},
	symbols = {
		File = { icon = '󰈮', hl = '@text.uri' },
		Module = { icon = '', hl = '@namespace' },
		Namespace = { icon = '', hl = '@namespace' },
		Package = { icon = '󰏖', hl = '@namespace' },
		Class = { icon = '𝓒', hl = '@type' },
		Method = { icon = 'ƒ', hl = '@method' },
		Property = { icon = '', hl = '@method' },
		Field = { icon = '󰽏', hl = '@field' },
		Constructor = { icon = '󱁤', hl = '@constructor' },
		Enum = { icon = 'ℰ', hl = '@type' },
		Interface = { icon = '', hl = '@type' },
		Function = { icon = '󰊕', hl = '@function' },
		Variable = { icon = '', hl = '@constant' },
		Constant = { icon = '', hl = '@constant' },
		String = { icon = '𝓐', hl = '@string' },
		Number = { icon = '#', hl = '@number' },
		Boolean = { icon = '', hl = '@boolean' },
		Array = { icon = '', hl = '@constant' },
		Object = { icon = '￼', hl = '@type' },
		Key = { icon = '󰌆', hl = '@type' },
		Null = { icon = 'NULL', hl = '@type' },
		EnumMember = { icon = '', hl = '@field' },
		Struct = { icon = '𝓢', hl = '@type' },
		Event = { icon = '🗲', hl = '@type' },
		Operator = { icon = '+', hl = '@operator' },
		TypeParameter = { icon = '𝙏', hl = '@parameter' },
		Component = { icon = '', hl = '@function' },
		Fragment = { icon = '', hl = '@constant' },
	},
}

vim.keymap.set('n', 'otl', '<CMD>SymbolsOutline<CR>')
