return {
    'phaazon/mind.nvim',
    branch = 'v2.2',
    event = 'VeryLazy',
    keys = {
        vim.keymap.set('n', 'mi', '<CMD>MindOpenMain<CR>'),
        vim.keymap.set('n', 'mo', '<CMD>MindOpenProject<CR>'),
        vim.keymap.set('n', 'pm', '<CMD>MindOpenSmartProject<CR>'),
        vim.keymap.set('n', 'mr', '<CMD>MindReloadState<CR>'),
        vim.keymap.set('n', 'cm', '<CMD>MindClose<CR>'),
    },
    config = function()
        require('mind').setup {
            persistence = {
                state_path = '~/.local/share/mind.nvim/mind.json',
                data_dir = '~/.local/share/mind.nvim/data',
            },
            edit = {
                data_extension = '.md',
                data_header = '# %s',
            },
            ui = {
                width = 40,
                root_marker = ' ',
                local_marker = ' ',
                data_marker = ' ',
                url_marker = ' ',
                select_marker = '⯇',
                icon_preset = {
                    { ' ', 'Root-project' },
                    { ' ', 'Sub-project' },
                    { ' ', 'Folder' },
                    { ' ', 'Tasks' },
                    { ' ', 'Uncheck' },
                    { ' ', 'On-going' },
                    { ' ', 'Done' },
                    { ' ', 'Important' },
                    { ' ', 'Fire' },
                    { '⯈ ', 'Indicator' },
                    { ' ', 'Git' },
                    { ' ', 'GitHub' },
                    { ' ', 'Neovim' },
                    { ' ', 'Lua' },
                    { ' ', 'Python' },
                    { ' ', 'HTML' },
                    { ' ', 'CSS' },
                    { ' ', 'JavaScript' },
                    { ' ', 'NodeJS' },
                    { ' ', 'Markdown' },
                    { ' ', 'Book' },
                    { ' ', 'Notes' },
                    { ' ', 'Idea' },
                    { ' ', 'On-hold' },
                    { ' ', 'Journal' },
                    { ' ', 'Monitoring' },
                    { ' ', 'Internet' },
                    { ' ', 'Rubbish' },
                },
            },
            keymaps = {
                normal = {
                    ['<CR>'] = 'open_data',
                    ['<S-CR>'] = 'open_data_index',
                    ['l'] = 'toggle_node',
                    ['h'] = 'toggle_node',
                    ['/'] = 'select_path',
                    ['i'] = 'change_icon_menu',
                    ii = 'add_inside_end_index',
                    as = 'add_inside_start',
                    ae = 'add_inside_end',
                    cl = 'copy_node_link',
                    cL = 'copy_node_link_index',
                    dl = 'delete',
                    df = 'delete_file',
                    re = 'rename',
                    ci = 'change_icon',
                    K = 'add_above',
                    J = 'add_below',
                    q = 'quit',
                    v = 'select',
                    u = 'make_url',
                },
                selection = {
                    ['<CR>'] = 'open_data',
                    ['l'] = 'toggle_node',
                    ['/'] = 'select_path',
                    ms = 'move_inside_start',
                    me = 'move_inside_end',
                    K = 'move_above',
                    J = 'move_below',
                    q = 'quit',
                    v = 'select',
                },
            },
        }
    end,
}
